apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  labels:
    {{- include "rds.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "rds.selectorLabels" . | nindent 4 }}
    app: auth
